### ISSUE TITLE
It will be great if the format matches JSONFeed

### ISSUE THREAD

**Issue by thejeshgn** [jimniels/readlists#14]
- Compatibility
- Ability to read in the feedreader
- Here is an example readlists in the JSONFeed format - https://data.thejeshgn.com/readlists/sri-lankas-economic-crisis.json

Thank you for amazing product. I love the UI.

**Comment by jimniels** [comment]
💯  need to do this!

**Comment by jimniels** [comment]
@thejeshgn done. Thanks for the suggestion!

**Comment by thejeshgn** [comment]
Thank you.
